---
- name: This is my first play
  hosts: mylocal
  tasks:
    - name: Initialize a terraform
      shell: ./terraform apply -input=false -auto-approve
      args:
        chdir: /home/shubham/terraform_files
      become: true
      register: teraaout

    - name: Show Terraform output
      debug:
        msg: "{{teraaout.stdout_lines}}"
